version: "2"
services:
  mpd:
    image: mpd
    ports:
      - "6600:6600"
    volumes:
      - mpd-data:/mpd/cache
      - /auto/music:/mpd/music
    build:
      context: ./docker-mpd
      dockerfile: Dockerfile
  filebeat:
    image: filebeat
    command: "-v"
    links:
      - redis:redis
    volumes:
      - mpd-data:/filebeat
      - filebeat-data:/var/lib/filebeat
      - ./filebeat-mpd-redis.yml:/etc/filebeat/filebeat.yml
    build:
      context: ./docker-filebeat
      dockerfile: Dockerfile
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
  resque_web:
    image: ennexa/resque-web
    ports:
      - "5678:5678"
    links:
      - redis:redis
    command: "-r redis://redis:6379"
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  mpd-data:
  redis-data:
  filebeat-data:
  elasticsearch-data:
